package com.example.gigsandcare.util

object Constants {

    // Buttons
    const val SIGN_IN_BUTTON = "Sign In"
    const val RESET_PASSWORD_BUTTON = "Reset"
    const val SIGN_UP_BUTTON = "Sign Up"
    const val GOOGLE_SIGN_IN_BUTTON = "Sign In with Google"
    const val GOOGLE_SIGN_UP_BUTTON = "Sign Up with Google"

    // Screens
    const val WELCOME_SCREEN = "Welcome"
    const val SIGN_IN_SCREEN = "Sign in"
    const val FORGOT_PASSWORD_SCREEN = "Forgot password"
    const val SIGN_UP_SCREEN = "Sign up"
    const val DASHBOARD_SCREEN = "Dashboard"
    const val HOME_SCREEN = "Home"
    const val HISTORY_SCREEN = "History"
    const val PROFILE_SCREEN = "Profile"
    const val PROGRAM_DETAIL_SCREEN = "Program Detail"
    const val BUY_TICKET_SCREEN = "Buy Ticket"
    const val SUCCESS_DONATION_SCREEN = "Success Donation"
    const val CHARITY_PROGRAM_SCREEN = "Charity Program"
    const val UPCOMING_CONCERT_SCREEN = "Upcoming Concert"

    // collection
    const val DONATE_COLLECTION = "userDonation"

    // Labels
    const val EMAIL_LABEL = "Email Address"
    const val PASSWORD_LABEL = "Password"

    // Useful
    const val EMPTY_STRING = ""

    // Texts
    const val TITLE = "Gigs & Care"
    const val WELCOME_TITLE = "All in one app that combine entertainment and social good"
    const val WELCOME_DESCRIPTION = "This app presents as an opportunity for users to contribute to charity without sacrificing their enjoyment"
    const val SIGN_UP_TITLE = "Create your new account"
    const val SIGN_UP_TITLE_WORD = "Create"
    const val SIGN_UP = "Sign Up"
    const val SIGN_IN_TITLE = "Sign in to your account"
    const val SIGN_IN = "Sign in"
    const val FORGOT_PASSWORD_TITLE = "Input your email to reset password"
    const val FORGOT_PASSWORD_TITLE_WORD = "reset password"
    const val FORGOT_PASSWORD = "Forgot Password"
    const val NO_ACCOUNT = "Don't have an account?"
    const val ALREADY_USER = "Already a user?"
    const val SEARCH = "Search"
    const val VIEW_ALL = "View All"
    const val TOP_PROGRAM = "Top Program"
    const val SHORTCUT = "Shortcut"
    const val ANOTHER_PROGRAM = "Another Program"
    const val CHARITY_PROGRAM = "Charity Program"
    const val UPCOMING_CONCERT = "Upcoming Concert"
    const val CHARITY_NEWS = "Charity News"
    const val EVENT_CALENDAR = "Event Calendar"
    const val CONCERT_LOCATION = "Concert Location"
    const val EDIT_PROFILE = "Edit Profile"
    const val NOTIFICATION_SETTINGS = "Notification Settings"
    const val NIGHT_MODE = "Night Mode"
    const val REMINDER_SOUND = "Reminder Sound"
    const val LOG_OUT = "Log Out"
    const val DONATION_GOAL = "Rp. 5.238.377"
    const val DONATION_DAYS_REMAINING = "15 Days Left"
    const val DONATION_PERCENTAGE = "34%"
    const val BUYING_TICKET_DONATION = "Buying Ticket & Donation"
    const val DONATION_ONLY = "Donation Only"
    const val HOW_MUCH_DONATE = "How much you want to donate?"
    const val INA_CURRENCY = "Rp."
    const val AMOUNT = "Amount"
    const val PAYMENT_METHOD = "Select your payment method"
    const val TEMP_PAYMENT_METHOD = "Mastercard / Visa"
    const val DONATE_NOW = "Donate Now!"
    const val SUCCESS_DONATION_TITLE = "Your transaction has been completed"
    const val SUCCESS_DONATION_DESCRIPTION = "To see transaction details and proof of payment, check your email"
    const val BACK_TO_HOME = "Back To Home"
    const val YOUR_ACTIVITY = "Your Activity"
    const val PEOPLES = "Peoples"
    const val PEOPLES_HELPED_DESC = "You helped"
    const val TOTAL_SPEND_FOR_CHARITY = "Total you spend for charity"
    const val PROGRAMS = "Programs"
    const val PROGRAMS_DESC = "Total of all programs"
    const val CONCERT_TICKET_PASS = "Concert Ticket 1 Day Pass"
    const val DONATION_FOR_CHARITY = "Donation For Charity"
    const val TOTAL = "Total"
    const val PAY_NOW = "Pay Now!"

    // image description
    const val GREEN_HOUSE = "Green house"
    const val PROFILE_PICTURE = "Profile Picture"
    const val WELCOME_PICTURE = "Welcome Picture"
}